### ISSUE TITLE
Integration with other languages

### ISSUE THREAD

**Issue by JannikStreek** [wartaal/HanTa#6]
Hi, 

great lib, helps a lot! I have built a small server wrapper, because I am not using python in my main project. With the small server, you can integrate HanTa also with other languages by calling a simple REST server. In my case, an elixir/phoenix application is using the server within a docker compose setup. Maybe it helps somebody else and, therefore, could be referenced in the readme. What do you think?

Link: https://github.com/b310-digital/nlp-word-tagger-server

Best regards from Hamburg
Jannik

**Comment by wartaal** [comment]
Hello Jannik,

thank you!Sure, I can mention it in the documentation and the readme. I am currently working on a few issues and on the documentation. I can include a reference to the wrapper in the next update!

Best wishes
Christian

**Comment by wartaal** [comment]
We just published a longer [documentation of HanTa](https://doi.org/10.25968/opus-2457). I included a link to your project.

**Comment by JannikStreek** [comment]
cool, thanks for all your work :)
